language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-21.0.0
    - android-21

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew clean testDebug -i